version: "3.9"
services:
  portfolio:
    build: .
    container_name: inkihong9.github.io
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
